Add Issuing Card and Issuing Cards List wrappers
stripe/react-connect-js pull request #52
Opened 2023-11-13 16:52 UTC by torrance-stripe

Adds support for Issuing Card and Issuing Cards List plus setter methods. Will rebase once base PR heads into `beta` and the `connect-js` package is bumped.

2023-11-14 17:43 UTC, jorgea-stripe requested changes

2023-11-14 17:43 UTC, jorgea-stripe commented on src/Components.tsx
> +    issuingCard.setDefaultCard(defaultCard);
You could implement these today with regular setAttributes, however the setter methods right now have race conditions, so we need to wait for those to be solved first

2023-11-16 20:57 UTC, jorgea-stripe commented on src/Components.tsx
> +    issuingCard.setDefaultCard(defaultCard);
To clarify we need to merge https://github.com/stripe/connect-js/pull/71#pullrequestreview-1735483336 , then publish, take a dependency on this repo, then we can merge this one

2023-11-17 15:54 UTC, jorgea-stripe commented on yarn.lock
> +"@stripe/connect-js@3.1.0-beta.1":
PR looks good, however is mising the package.json version bumps (in both the devDependencies and peerDependencies). We should also wait for https://github.com/stripe/react-connect-js/pull/53 to merge first

2023-11-17 16:33 UTC, jogonzal approved these changes

2023-11-17 16:33 UTC, jorgea-stripe approved these changes

2023-11-17 16:36 UTC, merged